// Interface translations: collect every t("...") text and build the catalogs module.
//
//   node scripts/i18n.mjs extract   -> shared/i18n/locales/en.json (the English source list)
//   node scripts/i18n.mjs build     -> shared/i18n/catalogs.ts from locales/<code>.json
//
// Translating en.json into each language is a separate step that needs the AI gateway key:
// scripts/i18n_translate.py (run on the server, see its docstring). This script only reads and writes files.
import fs from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..")
const dir = path.join(root, "shared", "i18n", "locales")
const SOURCES = ["src", "electron", "shared"]

function files(d) {
  return fs.readdirSync(d, { withFileTypes: true }).flatMap((e) => {
    const p = path.join(d, e.name)
    if (e.isDirectory()) return e.name === "i18n" || e.name === "node_modules" ? [] : files(p)
    return /\.(ts|tsx)$/.test(e.name) && !/\.test\./.test(e.name) ? [p] : []
  })
}

/** t("..."), t('...') and t(`...`) without interpolation; labels in shared/types.ts that are shown via t(label). */
export function extract() {
  const out = new Set()
  for (const file of SOURCES.flatMap((s) => files(path.join(root, s)))) {
    const src = fs.readFileSync(file, "utf8")
    for (const m of src.matchAll(/\bt\(\s*"((?:[^"\\]|\\.)*)"/g)) out.add(JSON.parse(`"${m[1]}"`))
    for (const m of src.matchAll(/\bt\(\s*'((?:[^'\\]|\\.)*)'/g)) out.add(m[1].replace(/\\'/g, "'"))
    for (const m of src.matchAll(/\bt\(\s*`([^`$]*)`/g)) out.add(m[1])
  }
  // Labels rendered with t(x.label) / t(LABELS[k]) live as data in shared/types.ts.
  const types = fs.readFileSync(path.join(root, "shared", "types.ts"), "utf8")
  for (const m of types.matchAll(/\blabel:\s*"((?:[^"\\]|\\.)*)"/g)) out.add(JSON.parse(`"${m[1]}"`))
  for (const block of types.matchAll(/export const \w+_LABELS[^=]*=\s*\{([\s\S]*?)\n\}/g)) {
    for (const m of block[1].matchAll(/:\s*"((?:[^"\\]|\\.)*)"/g)) out.add(JSON.parse(`"${m[1]}"`))
  }
  const sorted = [...out].filter((s) => s.trim()).sort()
  fs.mkdirSync(dir, { recursive: true })
  fs.writeFileSync(path.join(dir, "en.json"), JSON.stringify(sorted, null, 1) + "\n")
  // The languages to translate into: the ones Meetingly transcribes (LANGUAGES in shared/types.ts).
  const langs = [...types.matchAll(/\{ code: "(\w+)", name: "([^"]+)"/g)].map((m) => ({ code: m[1], name: m[2] }))
  fs.writeFileSync(path.join(dir, "languages.json"), JSON.stringify(langs, null, 1) + "\n")
  return sorted
}

/** catalogs.ts imports every locales/<code>.json that exists (en.json is the source list, not a catalog). */
export function build() {
  const codes = fs.existsSync(dir) ? fs.readdirSync(dir).filter((f) => /^[a-z]{2}\.json$/.test(f) && f !== "en.json").map((f) => f.slice(0, 2)).sort() : []
  const lines = [
    "// Generated by scripts/i18n.mjs from locales/*.json. Do not edit by hand.",
    'import type { LanguageCode } from "../types"',
    ...codes.map((c) => `import ${c} from "./locales/${c}.json"`),
    "",
    `export const CATALOGS: Partial<Record<LanguageCode, Record<string, string>>> = { ${codes.join(", ")} }`,
    ""
  ]
  fs.writeFileSync(path.join(root, "shared", "i18n", "catalogs.ts"), lines.join("\n"))
  return codes
}

const cmd = process.argv[2]
if (cmd === "extract") console.log(`${extract().length} strings -> shared/i18n/locales/en.json`)
else if (cmd === "build") console.log(`catalogs: ${build().join(", ") || "(none)"}`)
else if (cmd) console.error("usage: node scripts/i18n.mjs extract|build")
