import { LANGUAGES, type LanguageCode } from "../types"
import { CATALOGS } from "./catalogs"

/**
 * Interface translations. The English text in the code is the key: `t("Start listening")`, with
 * `{name}` placeholders for values. Catalogs (locales/<code>.json) map English to each language and
 * are generated by scripts/i18n.mjs; anything missing falls back to the English text.
 * Prompts sent to the model are never translated: the model answers in the output language.
 */

let locale: LanguageCode = "en"

/** The interface language: the user's choice, or the system's when it is one Meetingly speaks. */
export function resolveLocale(preference: LanguageCode | "auto", system: string): LanguageCode {
  if (preference !== "auto" && LANGUAGES.some((l) => l.code === preference)) return preference
  const base = system.toLowerCase().split(/[-_]/)[0]
  return LANGUAGES.find((l) => l.code === base)?.code ?? "en"
}

export function setLocale(code: LanguageCode): void {
  locale = code
}

export function getLocale(): LanguageCode {
  return locale
}

export function t(text: string, vars?: Record<string, string | number>): string {
  const translated = CATALOGS[locale]?.[text] || text
  if (!vars) return translated
  return translated.replace(/\{(\w+)\}/g, (match, key: string) => (key in vars ? String(vars[key]) : match))
}
